"""Telemetry package: immutable records and a thread-safe aggregator."""

from telemetry.aggregator import TelemetryAggregator
from telemetry.freshness import (
    GNSS_FRESHNESS,
    IMU_FRESHNESS,
    RGB_CAMERA_FRESHNESS,
    ContinuousFreshnessPolicy,
    OperationalHealth,
    SensorEvidence,
    SensorFreshness,
    SensorFreshnessConfig,
    SensorKind,
    SensorLifecycle,
    SensorReadiness,
    SensorStatus,
    evaluate_sensor_status,
)
from telemetry.state import (
    PIXEL_FORMAT_RGB8,
    ActorRef,
    CameraFrame,
    CameraFrameMetadata,
    CollisionEvent,
    EgoKinematics,
    EulerDegrees,
    GnssState,
    ImuState,
    LaneInvasionEvent,
    LaneMarkingInfo,
    SampleStamp,
    SensorHealth,
    TelemetrySnapshot,
    TransformState,
    Vector3,
    normalize_heading,
    speed_from_velocity,
    transform_state,
    vector_magnitude,
)

__all__ = [
    "TelemetryAggregator",
    "ContinuousFreshnessPolicy",
    "SensorFreshnessConfig",
    "GNSS_FRESHNESS",
    "IMU_FRESHNESS",
    "RGB_CAMERA_FRESHNESS",
    "SensorLifecycle",
    "SensorReadiness",
    "SensorFreshness",
    "OperationalHealth",
    "SensorKind",
    "SensorEvidence",
    "SensorStatus",
    "evaluate_sensor_status",
    "SampleStamp",
    "Vector3",
    "EulerDegrees",
    "TransformState",
    "EgoKinematics",
    "GnssState",
    "ImuState",
    "ActorRef",
    "CameraFrame",
    "CameraFrameMetadata",
    "PIXEL_FORMAT_RGB8",
    "CollisionEvent",
    "LaneMarkingInfo",
    "LaneInvasionEvent",
    "SensorHealth",
    "TelemetrySnapshot",
    "speed_from_velocity",
    "vector_magnitude",
    "normalize_heading",
    "transform_state",
]
